import { Country } from '../entities/country.entity';

export const countriesData: Partial<Country>[] = [
  {
    code: 'US',
    iso3: 'USA',
    name: 'United States',
    officialName: 'United States of America',
    currencyCode: 'USD',
    phoneCode: '+1',
    timezone: ['America/New_York', 'America/Chicago', 'America/Denver', 'America/Los_Angeles'],
    minWage: 7.25,
    standardWorkHours: 40,
    overtimeThreshold: 40,
    taxYearStart: '01-01',
    requiresWorkPermit: true,
    active: true,
  },
  {
    code: 'GB',
    iso3: 'GBR',
    name: 'United Kingdom',
    officialName: 'United Kingdom of Great Britain and Northern Ireland',
    currencyCode: 'GBP',
    phoneCode: '+44',
    timezone: ['Europe/London'],
    minWage: 10.42,
    standardWorkHours: 40,
    overtimeThreshold: 48,
    taxYearStart: '04-06',
    requiresWorkPermit: true,
    active: true,
  },
  {
    code: 'ZA',
    iso3: 'ZAF',
    name: 'South Africa',
    officialName: 'Republic of South Africa',
    currencyCode: 'ZAR',
    phoneCode: '+27',
    timezone: ['Africa/Johannesburg'],
    minWage: 25.42,
    standardWorkHours: 45,
    overtimeThreshold: 45,
    taxYearStart: '03-01',
    requiresWorkPermit: true,
    active: true,
  },
  {
    code: 'DE',
    iso3: 'DEU',
    name: 'Germany',
    officialName: 'Federal Republic of Germany',
    currencyCode: 'EUR',
    phoneCode: '+49',
    timezone: ['Europe/Berlin'],
    minWage: 12.00,
    standardWorkHours: 40,
    overtimeThreshold: 48,
    taxYearStart: '01-01',
    requiresWorkPermit: true,
    active: true,
  },
  {
    code: 'FR',
    iso3: 'FRA',
    name: 'France',
    officialName: 'French Republic',
    currencyCode: 'EUR',
    phoneCode: '+33',
    timezone: ['Europe/Paris'],
    minWage: 11.27,
    standardWorkHours: 35,
    overtimeThreshold: 35,
    taxYearStart: '01-01',
    requiresWorkPermit: true,
    active: true,
  },
  {
    code: 'JP',
    iso3: 'JPN',
    name: 'Japan',
    officialName: 'Japan',
    currencyCode: 'JPY',
    phoneCode: '+81',
    timezone: ['Asia/Tokyo'],
    minWage: 1004,
    standardWorkHours: 40,
    overtimeThreshold: 40,
    taxYearStart: '04-01',
    requiresWorkPermit: true,
    active: true,
  },
  {
    code: 'CN',
    iso3: 'CHN',
    name: 'China',
    officialName: "People's Republic of China",
    currencyCode: 'CNY',
    phoneCode: '+86',
    timezone: ['Asia/Shanghai'],
    minWage: 2590,
    standardWorkHours: 40,
    overtimeThreshold: 40,
    taxYearStart: '01-01',
    requiresWorkPermit: true,
    active: true,
  },
  {
    code: 'AU',
    iso3: 'AUS',
    name: 'Australia',
    officialName: 'Commonwealth of Australia',
    currencyCode: 'AUD',
    phoneCode: '+61',
    timezone: ['Australia/Sydney', 'Australia/Melbourne', 'Australia/Brisbane'],
    minWage: 23.23,
    standardWorkHours: 38,
    overtimeThreshold: 38,
    taxYearStart: '07-01',
    requiresWorkPermit: true,
    active: true,
  },
  {
    code: 'CA',
    iso3: 'CAN',
    name: 'Canada',
    officialName: 'Canada',
    currencyCode: 'CAD',
    phoneCode: '+1',
    timezone: ['America/Toronto', 'America/Vancouver', 'America/Edmonton'],
    minWage: 16.65,
    standardWorkHours: 40,
    overtimeThreshold: 44,
    taxYearStart: '01-01',
    requiresWorkPermit: true,
    active: true,
  },
  {
    code: 'IN',
    iso3: 'IND',
    name: 'India',
    officialName: 'Republic of India',
    currencyCode: 'INR',
    phoneCode: '+91',
    timezone: ['Asia/Kolkata'],
    minWage: 178,
    standardWorkHours: 48,
    overtimeThreshold: 48,
    taxYearStart: '04-01',
    requiresWorkPermit: true,
    active: true,
  },
];