import { Currency } from '../entities/currency.entity';

export const currenciesData: Partial<Currency>[] = [
  { code: 'USD', name: 'US Dollar', symbol: '$', decimalPlaces: 2, active: true },
  { code: 'EUR', name: 'Euro', symbol: '€', decimalPlaces: 2, active: true },
  { code: 'GBP', name: 'British Pound', symbol: '£', decimalPlaces: 2, active: true },
  { code: 'ZAR', name: 'South African Rand', symbol: 'R', decimalPlaces: 2, active: true },
  { code: 'JPY', name: 'Japanese Yen', symbol: '¥', decimalPlaces: 0, active: true },
  { code: 'CNY', name: 'Chinese Yuan', symbol: '¥', decimalPlaces: 2, active: true },
  { code: 'AUD', name: 'Australian Dollar', symbol: 'A$', decimalPlaces: 2, active: true },
  { code: 'CAD', name: 'Canadian Dollar', symbol: 'C$', decimalPlaces: 2, active: true },
  { code: 'CHF', name: 'Swiss Franc', symbol: 'Fr', decimalPlaces: 2, active: true },
  { code: 'INR', name: 'Indian Rupee', symbol: '₹', decimalPlaces: 2, active: true },
  { code: 'BRL', name: 'Brazilian Real', symbol: 'R$', decimalPlaces: 2, active: true },
  { code: 'MXN', name: 'Mexican Peso', symbol: '$', decimalPlaces: 2, active: true },
  { code: 'SGD', name: 'Singapore Dollar', symbol: 'S$', decimalPlaces: 2, active: true },
  { code: 'HKD', name: 'Hong Kong Dollar', symbol: 'HK$', decimalPlaces: 2, active: true },
  { code: 'NZD', name: 'New Zealand Dollar', symbol: 'NZ$', decimalPlaces: 2, active: true },
  { code: 'SEK', name: 'Swedish Krona', symbol: 'kr', decimalPlaces: 2, active: true },
  { code: 'NOK', name: 'Norwegian Krone', symbol: 'kr', decimalPlaces: 2, active: true },
  { code: 'DKK', name: 'Danish Krone', symbol: 'kr', decimalPlaces: 2, active: true },
  { code: 'PLN', name: 'Polish Zloty', symbol: 'zł', decimalPlaces: 2, active: true },
  { code: 'THB', name: 'Thai Baht', symbol: '฿', decimalPlaces: 2, active: true },
  { code: 'KRW', name: 'South Korean Won', symbol: '₩', decimalPlaces: 0, active: true },
  { code: 'IDR', name: 'Indonesian Rupiah', symbol: 'Rp', decimalPlaces: 0, active: true },
  { code: 'MYR', name: 'Malaysian Ringgit', symbol: 'RM', decimalPlaces: 2, active: true },
  { code: 'PHP', name: 'Philippine Peso', symbol: '₱', decimalPlaces: 2, active: true },
  { code: 'AED', name: 'UAE Dirham', symbol: 'د.إ', decimalPlaces: 2, active: true },
];